### ISSUE TITLE
Cannot open include file: 'dictionary.h': No such file or directory.

### ISSUE THREAD

**Issue by Avellea** [binogure-studio/godot-discord#1]
Hey there. I'm trying to compile this module but it says I am missing dictionary.h.

Full error is as follows.
```
scons: done reading SConscript files.                                                                                                                                                                                                        scons: Building targets ...                                                                                                                                                                                                                  [ 24%] Compiling ==> modules\godotdiscord\godotdiscord.cpp                                                                                                                                                                                   [ 24%] Compiling ==> modules\godotdiscord\register_types.cpp                                                                                                                                                                                 [ 24%] godotdiscord.cpp                                                                                                                                                                                                                      [ 24%] register_types.cpp                                                                                                                                                                                                                    [ 24%] modules\godotdiscord\register_types.cpp(1): fatal error C1083: Cannot open include file: 'globals.h': No such fil[ 24%] rectory                                                                                                       [ 25%] Compiling ==> thirdparty\mbedtls\library\aria.c                                                                                                                                                                                       [ 25%] Compiling ==> thirdparty\mbedtls\library\asn1parse.c                                                                                                                                                                                  aria.c                                                                                                                                                                                                                                       [ 25%] Compiling ==> thirdparty\mbedtls\library\asn1write.c                                                                                                                                                                                  asn1parse.c                                                                                                                                                                                                                                  [ 25%] Compiling ==> thirdparty\mbedtls\library\base64.c                                                                                                                                                                                     asn1write.c                                                                                                                                                                                                                                  base64.c                                                                                                                                                                                                                                     scons: *** [modules\godotdiscord\register_types.windows.tools.64.obj] Error 2                                                                                                                                                                Z:\Work\godot\modules\godotdiscord\godotdiscord.h(12): fatal error C1083: Cannot open include file: 'dictionary.h': No such file or directory                                                                                                scons: *** [modules\godotdiscord\godotdiscord.windows.tools.64.obj] Error 2                                                                                                                                                                  scons: building terminated because of errors. 
```

I would love to add Discord support to my game, and the other two most popular options do not work properly.

**Comment by xsellier** [comment]
This module is supposed to work with Godot Engine v2.1. It does not support v3.0+ yet.

**Comment by Avellea** [comment]
> 
> 
> This module is supposed to work with Godot Engine v2.1. It does not support v3.0+ yet.

Good to know. I'd suggest adding that to the readme, as it is a bit confusing at this point.

EDIT: Saw the change in README.md. Thanks!
